/**
 * Context Builder — generates CLAUDE.md content for spawned agents
 *
 * Each agent in a workflow run needs a CLAUDE.md that contains:
 *   1. Identity + communication rules (team name, leader, messaging protocol)
 *   2. Task description (from task entry)
 *   3. Role + responsibilities
 *   4. Project rules reference
 *   5. Workflow phases reference (AGENT-WORKFLOW-PHASES)
 *
 * When useWorktrees=false the built content is ALSO embedded inline in the
 * spawn prompt, because Claude Code issue #33045 means isolation:worktree
 * silently does not load CLAUDE.md for team agents.
 */

import type { TaskEntry } from './types';

// ─── Types ────────────────────────────────────────────────────

export interface ContextBuilderOptions {
  /** Feature / ticket slug (e.g. "workflow-standardization") */
  featureName: string;
  /** Team name for SendMessage routing (e.g. "workflow-standardization") */
  teamName: string;
  /** Name of the team leader agent to report to */
  teamLeaderName: string;
  /** Branch prefix for agent work branches (e.g. "work") */
  branchPrefix: string;
  /** Whether worktrees are in use (affects inline-injection warning) */
  useWorktrees: boolean;
  /** Absolute path to the project root (for path references in CLAUDE.md) */
  projectPath: string;
}

// ─── Builder ──────────────────────────────────────────────────

/**
 * Builds the CLAUDE.md string that is written into the agent's context
 * directory and, when useWorktrees=false, embedded directly in the prompt.
 *
 * NOTE (Claude Code #33045): `isolation: worktree` is silently ignored for
 * team agents — CLAUDE.md is NOT auto-loaded from worktrees when spawning
 * via the Agent tool in a team context. When useWorktrees=false the content
 * returned here must be embedded inline in the spawn prompt.
 */
export function buildAgentClaudeMd(
  task: TaskEntry,
  options: ContextBuilderOptions,
): string {
  const {
    featureName,
    teamName,
    teamLeaderName,
    branchPrefix,
    useWorktrees,
    projectPath,
  } = options;

  const workbranch = `${branchPrefix}/${featureName}/${task.taskSlug}`;
  const worktreePath = useWorktrees
    ? `${projectPath}/.worktrees/${featureName}/${task.taskSlug}`
    : null;

  const isolationNote = useWorktrees
    ? `Working directory: \`${worktreePath}\``
    : `**NOTE (Claude Code #33045)**: \`isolation: worktree\` is silently ignored for ` +
      `team agents — CLAUDE.md is not auto-loaded from worktrees. ` +
      `This context is embedded directly in your spawn prompt to compensate. ` +
      `Workbranch: \`${workbranch}\``;

  return `# Task Agent — ${task.taskName}

> Auto-generated by WorkflowEngine for feature: \`${featureName}\`
> Task #${String(task.taskNumber)} | Slug: \`${task.taskSlug}\` | Wave: ${String(task.wave)}
> Branch: \`${workbranch}\`

---

## Identity & Communication

You are a coding agent on team **"${teamName}"**.
Workbranch: \`${workbranch}\`
${isolationNote}

### Communication Rules (non-negotiable)

- Report ONLY to **"${teamLeaderName}"** via \`SendMessage\`.
- Do NOT message other agents. Do NOT spawn agents. Do NOT emit tracking events.
- On completion: \`SendMessage(to: "${teamLeaderName}", message: "Task #${String(task.taskNumber)} complete. Files: <list>. Self-review passed.", summary: "Task #${String(task.taskNumber)} done")\`
- On blocker: message leader immediately.
- Wait for shutdown_request when done.

---

## Workflow Phases

Read \`AGENT-WORKFLOW-PHASES.md\` (in your working directory under \`prompts/implementing-features/\`) and follow Phases 0–4 sequentially. Every coding agent MUST complete each phase — skipping phases is a CRITICAL VIOLATION.

---

## Task #${String(task.taskNumber)}: ${task.taskName}

**Slug**: \`${task.taskSlug}\`
**Wave**: ${String(task.wave)}
**Blocked By**: [${task.blockedBy.join(', ')}]
**Blocks**: [${task.blocks.join(', ')}]
**Task File**: \`${task.filePath}\`

Read your full task description, acceptance criteria, and file scope from the task file above.

---

## Project Rules

Read \`CLAUDE.md\` at the project root for all project conventions, architecture rules, and linting requirements. These are non-negotiable.

Key rules:
- Zero-tolerance linting policy — run \`npm run lint\` + \`npm run typecheck\` before marking done
- IPC: Zod schema in \`src/shared/ipc/<domain>/contract.ts\` — no business logic in handlers
- Services: factory pattern returning interface, \`import type\` for all interfaces
- UI: use \`@ui\` primitives — never raw HTML elements
- EVERY code change MUST update relevant docs

---

## Progress Tracking

Do NOT emit tracking events yourself — the team leader handles all \`/track\` calls.

Feature: \`${featureName}\`
Team: \`${teamName}\`
`;
}
